"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import tenant_service_group as shared_tenant_service_group
from dataclasses_json import Undefined, dataclass_json
from sase_tenancy import utils
from typing import Optional


@dataclasses.dataclass
class PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildrenRequest:
    
    tsg_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'tsg_id', 'style': 'simple', 'explode': False }})
    r"""A unique identifier for the tenant service group."""
    hierarchy: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'hierarchy', 'style': 'form', 'explode': True }})
    r"""If `true`, return the entire descendent hierarchy.
    If `false`, return only the immediate children of the
    TSG identified in this call's path. Default is
    `false`.
    """
    include_self: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'include_self', 'style': 'form', 'explode': True }})
    r"""Indicates if the TSG used to generate this hierarchy is
    included in the resulting TSG list. `true` to include
    self. Default is `false`.
    """
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildren200ApplicationJSON:
    r"""Successful response."""
    
    count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('count') }})
    r"""Total count of the items"""
    items: list[shared_tenant_service_group.TenantServiceGroup] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('items') }})
    

@dataclasses.dataclass
class PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildrenResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    post_tenancy_v1_tenant_service_groups_tsg_id_operations_list_children_200_application_json_object: Optional[PostTenancyV1TenantServiceGroupsTsgIDOperationsListChildren200ApplicationJSON] = dataclasses.field(default=None)
    r"""Successful response."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    